sudo: required

go_import_path: github.com/KyberNetwork/reserve-data

language: go

services:
  - docker

env:
  global:
    - GOMETALINTER_VERSION=2.0.11
    - PATH=$PATH:${TRAVIS_HOME}/gometalinter/gometalinter-${GOMETALINTER_VERSION}-linux-amd64
    
install:
  - ./.travis/gometalinter-install.sh
  - go get github.com/mattn/goveralls
  
cache: 
  directories:
  - ${TRAVIS_HOME}/gometalinter/gometalinter-${GOMETALINTER_VERSION}-linux-amd64

script:
  - gometalinter --config=gometalinter.json ./...
  - $GOPATH/bin/goveralls -v -race -service=travis-ci

after_success:
  - docker --version
  - docker build -f Dockerfile.next -t kybernetwork/reserve-data:$TRAVIS_COMMIT .

deploy:
  provider: script
  script: bash .travis/docker_push
  on:
    all_branches: true

go:
  - "1.10.x"
