FROM golang:1.13-stretch AS build-env

COPY . /reserve-data
WORKDIR /reserve-data/gateway/cmd
RUN go build -v -o /gateway

FROM debian:stretch
COPY --from=build-env /gateway /

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/gateway"]
