FROM golang:1.15-stretch AS build-env

COPY . /reserve-data
WORKDIR /reserve-data/reservesetting/cmd
RUN go build -v -o /setting

FROM debian:stretch
COPY --from=build-env /setting /
ADD  ./cmd/migrations /migrations
RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/setting","--migration-path","/migrations"]
