name: "Reserve Data CI"

on: push
env:
  GO111MODULE: on
  GOFLAGS: ""

jobs:
  # prepare the outputs to serve the next phases
  # allow branchs: all 
  prepare:
    runs-on: ubuntu-18.04
    outputs:
      current_branch: ${{ steps.current_branch.outputs.value }}
      tag: ${{ steps.tag.outputs.value }}
    steps:
      - name: Extract branch
        shell: bash
        id: current_branch
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          echo "::set-output name=value::$BRANCH"
      - name: Get Tag
        shell: bash
        id: tag
        run: |
          TAG="$(echo $GITHUB_SHA | head -c7)"
          echo "::set-output name=value::$TAG"
  
  # run lint check
  # allow branchs: all 
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.39.0
          args: -v --config .golangci.yml
  
  # test phase
  # allow branchs: all
  test:
    needs:
      - lint
    runs-on: ubuntu-18.04
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_PASSWORD: reserve_data
          POSTGRES_USER: reserve_data
          POSTGRES_DB: reserve_data
        # health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # map tcp port on container to the host
          - 5432:5432
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16.x"

      - name: Get Go cache paths
        id: cache_paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.cache_paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.cache_paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: Run test
        run: go test -v -race ./...

  # docker build and push kybernetwork/reserve-data
  # accept branchs: v3-develop, develop, v3-stagion, staging, master, github-action (just for test)
  build-next:
    needs:
      - prepare
      - test
    if: contains(fromJson('["v3-develop", "develop", "v3-staging", "staging", "master", "github-action"]'), needs.prepare.outputs.current_branch)
    runs-on: ubuntu-18.04
    env:
      IMAGE_NAME: kybernetwork/reserve-data
      BRANCH: ${{ needs.prepare.outputs.current_branch }}
      SHA_TAG: ${{ needs.prepare.outputs.tag }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-next-buildx

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.next
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.BRANCH }},${{ env.IMAGE_NAME }}:${{ env.SHA_TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  # docker build and push kybernetwork/reserve-data-gateway
  # accept branchs: v3-develop, develop, v3-stagion, staging, master, github-action (just for test)
  build-gateway:
    needs:
      - prepare
      - test
    if: contains(fromJson('["v3-develop", "develop", "v3-staging", "staging", "master", "github-action"]'), needs.prepare.outputs.current_branch)
    runs-on: ubuntu-18.04
    env:
      IMAGE_NAME: kybernetwork/reserve-data-gateway
      BRANCH: ${{ needs.prepare.outputs.current_branch }}
      SHA_TAG: ${{ needs.prepare.outputs.tag }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-gateway-buildx

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/Dockerfile.gateway
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.BRANCH }},${{ env.IMAGE_NAME }}:${{ env.SHA_TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  # docker build and push kybernetwork/reserve-data-setting
  # accept branchs: v3-develop, develop, v3-stagion, staging, master, github-action (just for test)
  build-setting:
    needs:
      - prepare
      - test
    if: contains(fromJson('["v3-develop", "develop", "v3-staging", "staging", "master", "github-action"]'), needs.prepare.outputs.current_branch)
    runs-on: ubuntu-18.04
    env:
      IMAGE_NAME: kybernetwork/reserve-data-setting
      BRANCH: ${{ needs.prepare.outputs.current_branch }}
      SHA_TAG: ${{ needs.prepare.outputs.tag }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-setting-buildx

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/Dockerfile.setting
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.BRANCH }},${{ env.IMAGE_NAME }}:${{ env.SHA_TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  # deploy awx using HTTP call
  # allow branchs: v3-develop, v3-staging
  deploy-awx:
    needs:
      - prepare
      - build-next
      - build-gateway
      - build-setting
    if: contains(fromJson('["v3-develop", "v3-staging"]'), needs.prepare.outputs.current_branch)
    runs-on: ubuntu-18.04
    env:
      BRANCH: ${{ needs.prepare.outputs.current_branch }}
      AWX_USERNAME: ${{ secrets.AWX_USERNAME }}
      AWX_PASSWORD: ${{ secrets.AWX_PASSWORD }}
      AWX_V3_DEV: ${{ secrets.AWX_V3_DEV }}
      AWX_V3_STG: ${{ secrets.AWX_V3_STG }}
    steps:
      - name: Notify to server
        run: |
          AWX_URL=$AWX_V3_DEV

          if [[ "$BRANCH" == "v3-staging" ]]; then
            AWX_URL=$AWX_V3_STG
          fi

          CODE=$(curl -XPOST -sSfL -w "%{http_code}" --user "$awx_username:$awx_password" $AWX_URL)
          [[ "$CODE" == 20* ]] || exit 1

  # deploy API docs to GCS
  # only branch `v3-develop`
  # TODO: need complete
  deploy-docs:
    needs:
      - prepare
      - test
    if: needs.prepare.outputs.current_branch == 'v3-develop'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build docs
        run: |
          docker run -v $PWD/apidocs/source:/slate/source:ro \
            -v $PWD/apidocs/build:/slate/build \
            kybernetwork/slate:latest
